### ISSUE TITLE
Explanation of purpose

### ISSUE THREAD

**Issue by johmarjac** [ChadSki/SharpNeedle#7]
Hi,

Why exactly is it necessary to load the entire CLR inside the C++ application? I did some testing yesterday and I got everything to work without loading the CLR inside.

My Launcher injects a C++ Library.
This C++ Library LoadLibrary the C# Dll
The C# Library has an exported function, which I can retrieve in the C++ Library using GetProcAddress just fine.

I typedef'd the exported function in the C++ library, created an instance of the typedef and assigned the return value of GetProcAddress.

When now calling the typedef'd function my exported function in my C# Dll is successfully called and the whole rest I can do from C# dll using unsafe or PInvoke.

So where is the point of loading the whole CLR?

**Comment by ChadSki** [comment]
C# code requires a CLR to run in. However you ran that managed code, a CLR was surely involved somehow.

Do you have a code example to share? Perhaps your C# dll is automatically bootstrapping a runspace for itself.

**Comment by johmarjac** [comment]
Yes, here: https://www.dropbox.com/s/fla8ynsr606e6y6/nativenet.zip?dl=0

Its a C++ Console loading the C# Dll using LoadLibrary, and they are calling each other methods

**Comment by marcussacana** [comment]
I worked with the DLLExport before, well man, the CLR is loaded when you call the export
![https://pomf.pyonpyon.moe/cwbjhq.png](https://pomf.pyonpyon.moe/cwbjhq.png)

**Comment by johmarjac** [comment]
Yeah, so that's actually good right? Saves a lot of time I guess.

**Comment by ChadSki** [comment]
Feel free to use RGiesecke.DllExport if it's more convenient for you. The CLR has to be loaded either way.

I'll also note that [DllExport](https://github.com/3F/DllExport) is about 12K lines of code, compared to SharpNeedle's 500 lines.

**Comment by johmarjac** [comment]
I see, so one can think SharpNeedle is an alternative to DllExport Project, just way less complex. Allright, everything I wanted to know, going to use SharpNeedle then. Thanks for your effort :)

**Comment by ChadSki** [comment]
One downside to SharpNeedle is I have not bothered to add 64-bit support yet. If you need that, DllExport might be a better option. Or you can upgrade SharpNeedle and submit a PR!

**Comment by johmarjac** [comment]
Hi,

so luckily, the process I want to inject to is x86. But if it comes to x64 sometimes and I need SharpNeedel I will likely try to add x64 support. 

Allright, I got it to work now. I dont know if that's correct or not, but after my function in c# finishs, it doesnt unload, nor does the clr. Is it possible to unload the clr + c# dll?

**Comment by ChadSki** [comment]
A good place to look would be the [ICLRRuntimeHost](https://docs.microsoft.com/en-us/dotnet/framework/unmanaged-api/hosting/iclrruntimehost-interface) documentation. You probably need the Stop and UnloadAppDomain methods. My personal usecase was injecting C# code that continues to run, so I didn't bother unloading anything except bootstrapper.dll.

Does DllExport unload the CLR for you? Honestly, that might be the better project to rely on unless you're set on learning the internals. SharpNeedle was mostly written because I had no alternative back then (DllExport didn't exist yet). I hoped it would serve as a good code example for other learners, but never planned on turning it into a polished library for diverse usecases.

**Comment by johmarjac** [comment]
Hi, thanks for your answer. DllExport doesn't. I used your project now in the hope to have more control.

I will look at the documentation. If i find anything and get it to work, i will create a pull request.

**Comment by johmarjac** [comment]
It seems it is not possible to unload the default AppDomain, or in general, it is not possible to free the resources of the CLR without terminating the process.
The documentation of [Stop()](https://docs.microsoft.com/en-us/dotnet/framework/unmanaged-api/hosting/iclrruntimehost-stop-method) also has the following important notice:

> This method does not release resources to the host, unload application domains, or destroy threads. You must terminate the process to release these resources.

But I have come up with a workaround. I´ve made one C# Dll which is invoked by the Bootstrapper, and that Dll then creates another AppDomain where I can load my actual assembly. I can load and unload the part of my program I actually wanted to be able to unload without terminating the process.

Anyways, thanks for your project, I am using it now as it is quite easy to understand.

**Comment by ChadSki** [comment]
Ah yeah, AppDomains seem like a good way to do that. Glad it's working for you!
